/*
 * Module catalog for the Mr. Worldwide fan-experience site.
 * Each module: id, category, name, tagline, description, oneTime (USD), monthly (USD),
 * weeks (build effort), tier (optional variants), qty (optional per-unit pricing),
 * requires (module ids), preview (how it renders in the landing mock).
 */
window.CATEGORIES = [
  { id: "core", name: "Core & Brand", icon: "🌍", blurb: "The foundation every configuration ships with." },
  { id: "ar", name: "WebAR Filters", icon: "🕶️", blurb: "Browser-based AR — no app download. Powered by 8th Wall / WebXR." },
  { id: "music", name: "Music & Releases", icon: "🎧", blurb: "Pre-saves, smart links and release moments." },
  { id: "tour", name: "Tour & Calendar", icon: "📅", blurb: "Dates, tickets and live moments." },
  { id: "fans", name: "Fan Engagement", icon: "🔥", blurb: "Membership, rewards and gamification." },
  { id: "commerce", name: "Commerce & Drops", icon: "🛒", blurb: "Merch, limited drops and digital collectibles." },
  { id: "content", name: "Content & Media", icon: "🎬", blurb: "Video, photos, news and press." },
  { id: "social", name: "Social & Community", icon: "📣", blurb: "UGC, challenges and shareable fan moments." },
  { id: "growth", name: "Data & Growth", icon: "📈", blurb: "Analytics, CRM and marketing plumbing." },
  { id: "ops", name: "Operations & Care", icon: "🛡️", blurb: "Hosting, compliance and ongoing support." },
];

window.MODULES = [
  { id: "hero", cat: "core", locked: true, name: "Hero Landing & Brand System", tagline: "Above-the-fold, Mr. Worldwide style", 
    desc: "Full-screen hero with video/3D loop, tagline, primary CTAs, custom typography and color system. Includes responsive framework, nav and footer.", oneTime: 2000, monthly: 0, ext: 0, extNote: "", days: 21, preview: "hero" },
  { id: "i18n", cat: "core", name: "Languages", tagline: "English + Spanish included - add any other language for $100 each", 
    desc: "The site comes in English and Spanish with a language switcher at the top. Each additional language (French, Italian, German, Dutch...) is +$100: we translate the whole site copy and add it to the switcher.", oneTime: 0, monthly: 0, ext: 0, extNote: "", days: 7, qty: {"label":"Add a language","min":0,"max":12,"unit":100,"unitMonthly":0,"included":["English","Spanish"],"options":["French","Italian","German","Dutch","Portuguese","Japanese","Korean","Mandarin","Arabic","Hindi","Russian","Turkish"]}, preview: "i18n" },
  { id: "capture", cat: "core", name: "Fan Capture (Email + SMS)", tagline: "Own the audience", 
    desc: "Newsletter + SMS opt-in with double opt-in, tagging by interest (tour, AR, merch), connected to Mailchimp / Klaviyo / Community.", oneTime: 350, monthly: 10, ext: 20, extNote: "Mailchimp / Klaviyo plan (grows with list size); SMS via Twilio pay-per-message", days: 7, preview: "capture" },
  { id: "cms", cat: "core", name: "Headless CMS & Admin", tagline: "Team edits without a developer", 
    desc: "Sanity / Strapi CMS with roles, drafts, scheduled publishing and image pipeline. Editors update tour dates, news, filters and drops.", oneTime: 300, monthly: 15, ext: 15, extNote: "Sanity / Strapi cloud plan", days: 14, preview: null },
  { id: "ar_face", cat: "ar", name: "Face Filters", tagline: "Shades, tux, 'Dale!' lens flares", 
    desc: "Face-tracked AR lenses (glasses, headwear, makeup, particle FX). Price per filter includes 3D asset, tracking tuning and QA on iOS/Android.", oneTime: 0, monthly: 0, ext: 99, extNote: "8th Wall WebAR license (per project)", days: 7, qty: {"label":"Number of face filters","min":1,"max":20,"unit":200,"unitMonthly":0,"default":3}, preview: "ar_face" },
  { id: "presave", cat: "music", name: "Pre-Save Campaign", tagline: "Spotify · Apple Music · Deezer · Amazon", 
    desc: "OAuth pre-save with follow-artist, auto-add to library on release day, fan data capture, thank-you page with exclusive filter unlock.", oneTime: 500, monthly: 10, ext: 20, extNote: "Pre-save platform (feature.fm) - $0 if we use own OAuth", days: 11, preview: "presave" },
  { id: "countdown", cat: "music", name: "Release Countdown & Reveal", tagline: "Tension until midnight", 
    desc: "Timezone-aware countdown, scheduled reveal of cover art/tracklist, confetti moment, auto-switch to smart links on release.", oneTime: 100, monthly: 0, ext: 0, extNote: "", days: 4, preview: "countdown" },
  { id: "smartlinks", cat: "music", name: "Smart Links & Discography", tagline: "Every release, every platform", 
    desc: "Auto-synced discography (Spotify API) with per-release smart link pages and embedded players.", oneTime: 150, monthly: 5, ext: 0, extNote: "", days: 7, preview: "smartlinks" },
  { id: "calendar", cat: "tour", name: "Tour Calendar", tagline: "Dates synced from Bandsintown / Songkick", 
    desc: "Interactive calendar + map view, auto-import, ticket links, 'notify me when he's near me' alerts, add-to-calendar (ICS/Google).", oneTime: 350, monthly: 5, ext: 0, extNote: "", days: 11, preview: "calendar" },
  { id: "tickets", cat: "tour", name: "Ticketing & Presale Codes", tagline: "Fan-club presale windows", 
    desc: "Ticketmaster / AXS deep links, unique presale codes distributed to members, waitlists per city.", oneTime: 100, monthly: 0, ext: 0, extNote: "", days: 7, 
    requires: ["calendar"], preview: "tickets" },
  { id: "vip", cat: "tour", name: "Meet & Greet / VIP Booking", tagline: "Bookable experiences with payments", 
    desc: "Slot booking, Stripe checkout, QR passes and reminders.", oneTime: 750, monthly: 10, ext: 0, extNote: "Stripe fees 2.9% + $0.30 per booking", days: 14, 
    requires: ["calendar"], preview: "vip" },
  { id: "fanclub", cat: "fans", name: "Fan Club Membership", tagline: "Free + paid tiers, single sign-on", 
    desc: "Social/email login, profile, tiered membership (Free / Dale / Worldwide) with Stripe subscriptions and perks gating.", oneTime: 400, monthly: 25, ext: 0, extNote: "Stripe fees 2.9% + $0.30 per paid membership", days: 21, preview: "fanclub" },
  { id: "points", cat: "fans", name: "Points & Rewards", tagline: "Earn for streams, shares, AR captures", 
    desc: "Points engine with rules, badges, streaks, reward catalog (presale, merch discounts, filter unlocks).", oneTime: 300, monthly: 10, ext: 0, extNote: "", days: 14, 
    requires: ["fanclub"], preview: "points" },
  { id: "leaderboard", cat: "fans", name: "Worldwide Leaderboard", tagline: "Top fans by country and city", 
    desc: "Global and per-country rankings, weekly reset, shareable rank cards.", oneTime: 100, monthly: 5, ext: 0, extNote: "", days: 7, 
    requires: ["points"], preview: "leaderboard" },
  { id: "contests", cat: "fans", name: "Contests & Giveaways", tagline: "Compliant sweepstakes engine", 
    desc: "Entry mechanics (share, capture, pre-save), T&Cs generator, random draw, winner notification.", oneTime: 150, monthly: 5, ext: 0, extNote: "", days: 11, preview: "contests" },
  { id: "quiz", cat: "fans", name: "'How Worldwide Are You?' Quiz", tagline: "Personality quiz with shareable result", 
    desc: "Branching quiz with result cards, unlocks a matching AR filter, drives email capture.", oneTime: 150, monthly: 0, ext: 0, extNote: "", days: 7, preview: "quiz" },
  { id: "fancard", cat: "fans", name: "Fan Card Generator", tagline: "Wrapped-style personal stats card", 
    desc: "Pulls Spotify listening data (with consent) to render a personalised 'Mr. Worldwide Passport' image for sharing.", oneTime: 200, monthly: 5, ext: 0, extNote: "", days: 11, preview: "fancard" },
  { id: "birthday", cat: "fans", name: "Personalised Video Messages", tagline: "AI-cloned voice shout-outs (with approval)", 
    desc: "Fans request a birthday / graduation shout-out; approved template videos rendered with fan's name. Consent + review workflow.", oneTime: 250, monthly: 25, ext: 30, extNote: "AI voice license (ElevenLabs)", days: 18, 
    requires: ["fanclub"], preview: "birthday" },
  { id: "fanwall", cat: "fans", name: "Fan Wall & Comments", tagline: "Moderated community feed", 
    desc: "Threaded posts, reactions, profanity filter, report flow, pinned artist posts.", oneTime: 200, monthly: 10, ext: 0, extNote: "", days: 14, 
    requires: ["fanclub"], preview: "fanwall" },
  { id: "store", cat: "commerce", name: "Merch Store", tagline: "Shopify headless, on-brand checkout", 
    desc: "Product grid, variants, cart, Shopify checkout, inventory sync, regional pricing and taxes.", oneTime: 350, monthly: 10, ext: 39, extNote: "Shopify Basic plan + payment fees", days: 21, preview: "store" },
  { id: "drops", cat: "commerce", name: "Limited Drops & Queue", tagline: "Hype releases without crashing", 
    desc: "Countdown drops, virtual waiting room, per-fan purchase limits, member-early-access.", oneTime: 200, monthly: 10, ext: 0, extNote: "", days: 11, 
    requires: ["store"], preview: "drops" },
  { id: "collectibles", cat: "commerce", name: "Digital Collectibles", tagline: "Stamps, AR unlockables, optional on-chain", 
    desc: "Collect digital passport stamps per show / release / filter; optional wallet-less NFT minting (Polygon) for verified scarcity.", oneTime: 200, monthly: 10, ext: 0, extNote: "Blockchain gas fees only if on-chain", days: 14, preview: "collectibles" },
  { id: "bundles", cat: "commerce", name: "Album + Merch Bundles", tagline: "Chart-eligible D2C bundles", 
    desc: "Bundle builder, vinyl/CD pre-orders, fulfilment partner integration, chart-reporting exports.", oneTime: 150, monthly: 0, ext: 0, extNote: "", days: 7, 
    requires: ["store"], preview: null },
  { id: "donate", cat: "commerce", name: "Foundation & Causes", tagline: "SLAM! schools, disaster relief", 
    desc: "Donation flow, impact counters and campaign pages for the artist's philanthropy.", oneTime: 100, monthly: 0, ext: 0, extNote: "", days: 7, preview: "donate" },
  { id: "sponsors", cat: "commerce", name: "Sponsor & Brand Zones", tagline: "Monetise the traffic", 
    desc: "Branded filter placements, sponsor modules with impression reporting and custom landing pages.", oneTime: 100, monthly: 0, ext: 0, extNote: "", days: 7, preview: null },
  { id: "news", cat: "content", name: "News & Announcements", tagline: "Editorial hub", 
    desc: "Article pages, categories, rich embeds, SEO schema, RSS.", oneTime: 100, monthly: 0, ext: 0, extNote: "", days: 7, 
    requires: ["cms"], preview: "news" },
  { id: "video", cat: "content", name: "Video Hub", tagline: "Music videos, BTS, interviews", 
    desc: "YouTube/Vimeo sync, playlists, chapters, autoplay grid.", oneTime: 100, monthly: 5, ext: 0, extNote: "", days: 7, preview: "video" },
  { id: "gallery", cat: "content", name: "Photo Gallery", tagline: "Tour, red carpet, studio", 
    desc: "Masonry galleries with lightbox, albums per tour date, download-for-fans option.", oneTime: 80, monthly: 5, ext: 0, extNote: "", days: 4, preview: "gallery" },
  { id: "timeline", cat: "content", name: "Career Timeline", tagline: "From Miami to Mr. Worldwide", 
    desc: "Scroll-driven interactive biography with milestones, awards and media.", oneTime: 100, monthly: 0, ext: 0, extNote: "", days: 11, preview: "timeline" },
  { id: "podcast", cat: "content", name: "Podcast / Audio Series", tagline: "Motivational drops from Mr. 305", 
    desc: "Episode pages, RSS feed, embedded player, transcripts.", oneTime: 80, monthly: 5, ext: 0, extNote: "", days: 7, preview: null },
  { id: "press", cat: "content", name: "Press & Partners Kit", tagline: "Bios, photos, logos, rider", 
    desc: "Gated download area for press and promoters with usage terms.", oneTime: 60, monthly: 0, ext: 0, extNote: "", days: 4, preview: null },
  { id: "worldmap", cat: "social", name: "Worldwide Fan Map", tagline: "Live pins from every fan check-in", 
    desc: "Real-time globe of fan check-ins and AR captures; per-country counters; heat during shows.", oneTime: 150, monthly: 10, ext: 0, extNote: "Mapbox free tier up to 50k loads/month", days: 14, preview: "worldmap" },
  { id: "analytics", cat: "growth", name: "Analytics & Fan Dashboard (Google Analytics)", tagline: "GA4 with 10 tracked events + your own segmented dashboard", 
    desc: "Google Analytics 4 wired into the whole site with 10 tracked events included (page views, AR filter opens, pre-saves, ticket clicks, sign-ups, merch clicks, shares, video plays, language, country). Includes a private dashboard page where your team sees all metrics segmented by country, device, campaign and fan tier. Each extra event to track is +$50.", oneTime: 500, monthly: 15, ext: 0, extNote: "", days: 14, preview: "analytics",
    qty: { label: "Extra events to track", min: 0, max: 30, unit: 50, unitMonthly: 0, default: 0 } },
  { id: "seo", cat: "growth", name: "SEO & Performance Pass", tagline: "Core Web Vitals green", 
    desc: "Technical SEO, structured data, image/CDN optimisation, Lighthouse ≥ 90.", oneTime: 100, monthly: 0, ext: 0, extNote: "", days: 7, preview: null },
  { id: "hosting", cat: "ops", locked: true, name: "Hosting, CDN & Security", tagline: "Vercel/Cloudflare, global edge", 
    desc: "Edge hosting, DDoS protection, SSL, daily backups, monitoring. Scales for drop-night traffic spikes.", oneTime: 250, monthly: 25, ext: 20, extNote: "Vercel Pro / Cloudflare plan", days: 4, preview: null },
  { id: "a11y", cat: "ops", name: "Accessibility (WCAG 2.2 AA)", tagline: "Everyone gets in", 
    desc: "Audit + remediation, captions, reduced-motion modes, AR alternatives.", oneTime: 100, monthly: 0, ext: 0, extNote: "", days: 7, preview: null },
  { id: "support", cat: "ops", name: "Maintenance & Support Retainer", tagline: "Updates, monitoring, small changes", 
    desc: "Monthly hours for content help, dependency updates and new filter QA.", oneTime: 0, monthly: 0, ext: 0, extNote: "", days: 0, tier: { label: "Retainer level", options: [
      {"id":"basic","name":"Basic — 4 h/mo","oneTime":0,"monthly":150},
      {"id":"pro","name":"Pro — 10 h/mo, 24h SLA","oneTime":0,"monthly":350},
      {"id":"tour","name":"Tour mode — on-call during shows","oneTime":0,"monthly":700} ] }, preview: null },
];

/* Pre-built bundles the client can start from */
window.PRESETS = [
  { id: "starter", name: "Starter", blurb: "≈ $5k — landing + AR filters + pre-save + calendar.",
    modules: ["hero", "hosting", "capture", "ar_face", "presave", "calendar"] },
  { id: "fan", name: "Fan Experience", blurb: "≈ $8k — adds more filters, fan club, rewards, store.",
    modules: ["hero", "hosting", "i18n", "capture", "cms", "ar_face",
      "presave", "countdown", "smartlinks", "calendar", "tickets", "fanclub", "points", "quiz", "fancard", "store", "video", "support"] },
  { id: "worldwide", name: "Mr. Worldwide", blurb: "≈ $15k — everything: livestream, collectibles, fan map, full retainer.",
    modules: "all" },
];

/* Budget bands the proposal is aimed at (one-time build) */
window.BUDGETS = [
  { id: "base", name: "Base", max: 5000 },
  { id: "mid", name: "Mid", max: 8000 },
  { id: "top", name: "Top", max: 15000 },
];
