/*
 * Module catalog for the Mr. Worldwide fan-experience site.
 * Each module: id, category, name, tagline, description, oneTime (USD), monthly (USD),
 * weeks (build effort), tier (optional variants), qty (optional per-unit pricing),
 * requires (module ids), preview (how it renders in the landing mock).
 */
window.CATEGORIES = [
  { id: "core", name: "Core & Brand", icon: "🌍", blurb: "The foundation every configuration ships with." },
  { id: "ar", name: "WebAR Filter Hub", icon: "🕶️", blurb: "Browser-based AR — no app download. Powered by 8th Wall / WebXR." },
  { id: "music", name: "Music & Releases", icon: "🎧", blurb: "Pre-saves, smart links and release moments." },
  { id: "tour", name: "Tour & Calendar", icon: "📅", blurb: "Dates, tickets and live moments." },
  { id: "fans", name: "Fan Engagement", icon: "🔥", blurb: "Membership, rewards and gamification." },
  { id: "commerce", name: "Commerce & Drops", icon: "🛒", blurb: "Merch, limited drops and digital collectibles." },
  { id: "content", name: "Content & Media", icon: "🎬", blurb: "Video, photos, news and press." },
  { id: "social", name: "Social & Community", icon: "📣", blurb: "UGC, challenges and shareable fan moments." },
  { id: "growth", name: "Data & Growth", icon: "📈", blurb: "Analytics, CRM and marketing plumbing." },
  { id: "ops", name: "Operations & Care", icon: "🛡️", blurb: "Hosting, compliance and ongoing support." },
];

window.MODULES = [
  { id: "hero", cat: "core", locked: true, name: "Hero Landing & Brand System", tagline: "Above-the-fold, Mr. Worldwide style", 
    desc: "Full-screen hero with video/3D loop, tagline, primary CTAs, custom typography and color system. Includes responsive framework, nav and footer.", oneTime: 2000, monthly: 0, weeks: 3, preview: "hero" },
  { id: "i18n", cat: "core", name: "Bilingual EN / ES (+ more)", tagline: "Dale, worldwide means worldwide", 
    desc: "Language switcher with full content localization. Additional languages billed per language.", oneTime: 250, monthly: 0, weeks: 1, qty: {"label":"Extra languages (PT, FR, DE…)","min":0,"max":8,"unit":100,"unitMonthly":0}, preview: "i18n" },
  { id: "capture", cat: "core", name: "Fan Capture (Email + SMS)", tagline: "Own the audience", 
    desc: "Newsletter + SMS opt-in with double opt-in, tagging by interest (tour, AR, merch), connected to Mailchimp / Klaviyo / Community.", oneTime: 350, monthly: 10, weeks: 1, preview: "capture" },
  { id: "cms", cat: "core", name: "Headless CMS & Admin", tagline: "Team edits without a developer", 
    desc: "Sanity / Strapi CMS with roles, drafts, scheduled publishing and image pipeline. Editors update tour dates, news, filters and drops.", oneTime: 300, monthly: 15, weeks: 2, preview: null },
  { id: "pwa", cat: "core", name: "PWA — Install to Home Screen", tagline: "App feel, no app store", 
    desc: "Offline shell, install prompt, splash screens, app icon. Basis for push notifications.", oneTime: 150, monthly: 0, weeks: 1, preview: null },
  { id: "ar_hub", cat: "ar", name: "WebAR Filter Hub", tagline: "The gallery that hosts every filter", 
    desc: "Filter gallery with thumbnails, categories, QR handoff from desktop to phone, camera permission flow, device compatibility fallback. Includes 8th Wall / Zappar commercial license setup.", oneTime: 850, monthly: 50, weeks: 3, preview: "ar_hub" },
  { id: "ar_face", cat: "ar", name: "Face Filters", tagline: "Shades, tux, 'Dale!' lens flares", 
    desc: "Face-tracked AR lenses (glasses, headwear, makeup, particle FX). Price per filter includes 3D asset, tracking tuning and QA on iOS/Android.", oneTime: 0, monthly: 0, weeks: 1, 
    requires: ["ar_hub"], qty: {"label":"Number of face filters","min":1,"max":20,"unit":200,"unitMonthly":0,"default":3}, preview: "ar_face" },
  { id: "ar_world", cat: "ar", name: "World AR — Pitbull in Your Room", tagline: "Volumetric / 3D performer placement", 
    desc: "Surface-tracked AR: place a 3D or volumetric-captured Pitbull performing a snippet in the fan's space. Includes volumetric capture session coordination or stylized 3D avatar.", oneTime: 0, monthly: 0, weeks: 4, 
    requires: ["ar_hub"], tier: { label: "Avatar type", options: [
      {"id":"avatar3d","name":"Stylized 3D avatar","oneTime":600,"monthly":0},
      {"id":"volumetric","name":"Volumetric capture (real Pitbull)","oneTime":1000,"monthly":0} ] }, preview: "ar_world" },
  { id: "ar_marker", cat: "ar", name: "Image-Target AR", tagline: "Scan the album cover, poster or ticket", 
    desc: "Album art, tour posters, merch tags and tickets come alive with video, 3D and links. Per target pricing.", oneTime: 100, monthly: 0, weeks: 1, 
    requires: ["ar_hub"], qty: {"label":"Image targets","min":1,"max":15,"unit":100,"unitMonthly":0,"default":2}, preview: "ar_marker" },
  { id: "ar_tryon", cat: "ar", name: "AR Merch Try-On", tagline: "Caps, tees, chains — try before buy", 
    desc: "Body/face-tracked try-on of merch items with direct add-to-cart. Per SKU 3D modelling included.", oneTime: 150, monthly: 0, weeks: 2, 
    requires: ["ar_hub"], qty: {"label":"Merch SKUs modelled","min":1,"max":30,"unit":50,"unitMonthly":0,"default":4}, preview: "ar_tryon" },
  { id: "ar_booth", cat: "ar", name: "AR Photo & Video Booth", tagline: "Capture, brand, share in one tap", 
    desc: "Record 15s clips or photos with the active filter, branded watermark + hashtag, native share sheet to TikTok/IG/WhatsApp, download.", oneTime: 250, monthly: 10, weeks: 1.5, 
    requires: ["ar_hub"], preview: "ar_booth" },
  { id: "ar_drops", cat: "ar", name: "Timed & Geo-Fenced Filter Drops", tagline: "Only in Miami. Only tonight.", 
    desc: "Unlock filters by date window, GPS geofence (venue/city) or QR at the show. Countdown teaser cards for upcoming filters.", oneTime: 200, monthly: 10, weeks: 2, 
    requires: ["ar_hub"], preview: "ar_drops" },
  { id: "ar_portal", cat: "ar", name: "AR Portal — Walk into the Show", tagline: "360° concert portal in your living room", 
    desc: "Step-through portal into a 360° concert / backstage video environment with spatial audio.", oneTime: 350, monthly: 0, weeks: 3, 
    requires: ["ar_hub"], preview: "ar_portal" },
  { id: "ar_ugc", cat: "ar", name: "UGC Wall (Moderated)", tagline: "Fan-made AR moments, curated", 
    desc: "Fans submit booth captures; moderation queue with AI pre-screening; approved posts appear on a live wall and can be pushed to venue screens.", oneTime: 150, monthly: 15, weeks: 2, 
    requires: ["ar_booth"], preview: "ar_ugc" },
  { id: "ar_analytics", cat: "ar", name: "AR Analytics", tagline: "Sessions, dwell time, shares, devices", 
    desc: "Per-filter funnel: opens → camera granted → capture → share. Exports for sponsors.", oneTime: 100, monthly: 5, weeks: 1, 
    requires: ["ar_hub"], preview: null },
  { id: "presave", cat: "music", name: "Pre-Save Campaign", tagline: "Spotify · Apple Music · Deezer · Amazon", 
    desc: "OAuth pre-save with follow-artist, auto-add to library on release day, fan data capture, thank-you page with exclusive filter unlock.", oneTime: 500, monthly: 10, weeks: 1.5, preview: "presave" },
  { id: "countdown", cat: "music", name: "Release Countdown & Reveal", tagline: "Tension until midnight", 
    desc: "Timezone-aware countdown, scheduled reveal of cover art/tracklist, confetti moment, auto-switch to smart links on release.", oneTime: 100, monthly: 0, weeks: 0.5, preview: "countdown" },
  { id: "smartlinks", cat: "music", name: "Smart Links & Discography", tagline: "Every release, every platform", 
    desc: "Auto-synced discography (Spotify API) with per-release smart link pages and embedded players.", oneTime: 150, monthly: 5, weeks: 1, preview: "smartlinks" },
  { id: "player", cat: "music", name: "Persistent Mini Player", tagline: "Music keeps playing as fans browse", 
    desc: "Sticky player with previews / full Spotify Web Playback for logged-in premium users.", oneTime: 100, monthly: 0, weeks: 1, preview: "player" },
  { id: "lyrics", cat: "music", name: "Lyrics & Translations", tagline: "Sing along in EN/ES", 
    desc: "Synced lyrics per track with bilingual toggle and share-a-line cards.", oneTime: 100, monthly: 5, weeks: 1, preview: null },
  { id: "playlist", cat: "music", name: "Fan Co-Created Playlist", tagline: "Fans vote the pre-show playlist", 
    desc: "Fans submit and up-vote tracks; winning playlist published to Spotify weekly.", oneTime: 100, monthly: 5, weeks: 1, preview: "playlist" },
  { id: "calendar", cat: "tour", name: "Tour Calendar", tagline: "Dates synced from Bandsintown / Songkick", 
    desc: "Interactive calendar + map view, auto-import, ticket links, 'notify me when he's near me' alerts, add-to-calendar (ICS/Google).", oneTime: 350, monthly: 5, weeks: 1.5, preview: "calendar" },
  { id: "tickets", cat: "tour", name: "Ticketing & Presale Codes", tagline: "Fan-club presale windows", 
    desc: "Ticketmaster / AXS deep links, unique presale codes distributed to members, waitlists per city.", oneTime: 100, monthly: 0, weeks: 1, 
    requires: ["calendar"], preview: "tickets" },
  { id: "setlist", cat: "tour", name: "Setlist Voting", tagline: "Fans pick one song per show", 
    desc: "Per-city poll open until doors; results feed a screen backstage and a post-show recap.", oneTime: 100, monthly: 5, weeks: 1, 
    requires: ["calendar"], preview: "setlist" },
  { id: "vip", cat: "tour", name: "Meet & Greet / VIP Booking", tagline: "Bookable experiences with payments", 
    desc: "Slot booking, Stripe checkout, QR passes and reminders.", oneTime: 200, monthly: 10, weeks: 2, 
    requires: ["calendar"], preview: "vip" },
  { id: "livestream", cat: "tour", name: "Livestream & Watch Party", tagline: "PPV or free, with live chat", 
    desc: "Mux / Vimeo OTT player, paywall option, live chat with emoji reactions, replay window.", oneTime: 300, monthly: 25, weeks: 2, preview: "livestream" },
  { id: "afterparty", cat: "tour", name: "Post-Show Recap Pages", tagline: "Auto-generated per city", 
    desc: "Photos, setlist, fan captures and next-city teaser published automatically after each date.", oneTime: 100, monthly: 5, weeks: 1, 
    requires: ["calendar"], preview: null },
  { id: "fanclub", cat: "fans", name: "Fan Club Membership", tagline: "Free + paid tiers, single sign-on", 
    desc: "Social/email login, profile, tiered membership (Free / Dale / Worldwide) with Stripe subscriptions and perks gating.", oneTime: 400, monthly: 25, weeks: 3, preview: "fanclub" },
  { id: "points", cat: "fans", name: "Points & Rewards", tagline: "Earn for streams, shares, AR captures", 
    desc: "Points engine with rules, badges, streaks, reward catalog (presale, merch discounts, filter unlocks).", oneTime: 300, monthly: 10, weeks: 2, 
    requires: ["fanclub"], preview: "points" },
  { id: "leaderboard", cat: "fans", name: "Worldwide Leaderboard", tagline: "Top fans by country and city", 
    desc: "Global and per-country rankings, weekly reset, shareable rank cards.", oneTime: 100, monthly: 5, weeks: 1, 
    requires: ["points"], preview: "leaderboard" },
  { id: "contests", cat: "fans", name: "Contests & Giveaways", tagline: "Compliant sweepstakes engine", 
    desc: "Entry mechanics (share, capture, pre-save), T&Cs generator, random draw, winner notification.", oneTime: 150, monthly: 5, weeks: 1.5, preview: "contests" },
  { id: "quiz", cat: "fans", name: "'How Worldwide Are You?' Quiz", tagline: "Personality quiz with shareable result", 
    desc: "Branching quiz with result cards, unlocks a matching AR filter, drives email capture.", oneTime: 150, monthly: 0, weeks: 1, preview: "quiz" },
  { id: "fancard", cat: "fans", name: "Fan Card Generator", tagline: "Wrapped-style personal stats card", 
    desc: "Pulls Spotify listening data (with consent) to render a personalised 'Mr. Worldwide Passport' image for sharing.", oneTime: 200, monthly: 5, weeks: 1.5, preview: "fancard" },
  { id: "push", cat: "fans", name: "Push & WhatsApp Notifications", tagline: "Filter drop live. Tickets on sale. Dale.", 
    desc: "Web push (via PWA) + WhatsApp Business broadcast with segmentation.", oneTime: 150, monthly: 15, weeks: 1, 
    requires: ["pwa"], preview: null },
  { id: "birthday", cat: "fans", name: "Personalised Video Messages", tagline: "AI-cloned voice shout-outs (with approval)", 
    desc: "Fans request a birthday / graduation shout-out; approved template videos rendered with fan's name. Consent + review workflow.", oneTime: 250, monthly: 25, weeks: 2.5, 
    requires: ["fanclub"], preview: "birthday" },
  { id: "fanwall", cat: "fans", name: "Fan Wall & Comments", tagline: "Moderated community feed", 
    desc: "Threaded posts, reactions, profanity filter, report flow, pinned artist posts.", oneTime: 200, monthly: 10, weeks: 2, 
    requires: ["fanclub"], preview: "fanwall" },
  { id: "store", cat: "commerce", name: "Merch Store", tagline: "Shopify headless, on-brand checkout", 
    desc: "Product grid, variants, cart, Shopify checkout, inventory sync, regional pricing and taxes.", oneTime: 350, monthly: 10, weeks: 3, preview: "store" },
  { id: "drops", cat: "commerce", name: "Limited Drops & Queue", tagline: "Hype releases without crashing", 
    desc: "Countdown drops, virtual waiting room, per-fan purchase limits, member-early-access.", oneTime: 200, monthly: 10, weeks: 1.5, 
    requires: ["store"], preview: "drops" },
  { id: "collectibles", cat: "commerce", name: "Digital Collectibles", tagline: "Stamps, AR unlockables, optional on-chain", 
    desc: "Collect digital passport stamps per show / release / filter; optional wallet-less NFT minting (Polygon) for verified scarcity.", oneTime: 200, monthly: 10, weeks: 2, preview: "collectibles" },
  { id: "bundles", cat: "commerce", name: "Album + Merch Bundles", tagline: "Chart-eligible D2C bundles", 
    desc: "Bundle builder, vinyl/CD pre-orders, fulfilment partner integration, chart-reporting exports.", oneTime: 150, monthly: 0, weeks: 1, 
    requires: ["store"], preview: null },
  { id: "donate", cat: "commerce", name: "Foundation & Causes", tagline: "SLAM! schools, disaster relief", 
    desc: "Donation flow, impact counters and campaign pages for the artist's philanthropy.", oneTime: 100, monthly: 0, weeks: 1, preview: "donate" },
  { id: "sponsors", cat: "commerce", name: "Sponsor & Brand Zones", tagline: "Monetise the traffic", 
    desc: "Branded filter placements, sponsor modules with impression reporting and custom landing pages.", oneTime: 100, monthly: 0, weeks: 1, preview: null },
  { id: "news", cat: "content", name: "News & Announcements", tagline: "Editorial hub", 
    desc: "Article pages, categories, rich embeds, SEO schema, RSS.", oneTime: 100, monthly: 0, weeks: 1, 
    requires: ["cms"], preview: "news" },
  { id: "video", cat: "content", name: "Video Hub", tagline: "Music videos, BTS, interviews", 
    desc: "YouTube/Vimeo sync, playlists, chapters, autoplay grid.", oneTime: 100, monthly: 5, weeks: 1, preview: "video" },
  { id: "gallery", cat: "content", name: "Photo Gallery", tagline: "Tour, red carpet, studio", 
    desc: "Masonry galleries with lightbox, albums per tour date, download-for-fans option.", oneTime: 80, monthly: 5, weeks: 0.5, preview: "gallery" },
  { id: "timeline", cat: "content", name: "Career Timeline", tagline: "From Miami to Mr. Worldwide", 
    desc: "Scroll-driven interactive biography with milestones, awards and media.", oneTime: 100, monthly: 0, weeks: 1.5, preview: "timeline" },
  { id: "podcast", cat: "content", name: "Podcast / Audio Series", tagline: "Motivational drops from Mr. 305", 
    desc: "Episode pages, RSS feed, embedded player, transcripts.", oneTime: 80, monthly: 5, weeks: 1, preview: null },
  { id: "press", cat: "content", name: "Press & Partners Kit", tagline: "Bios, photos, logos, rider", 
    desc: "Gated download area for press and promoters with usage terms.", oneTime: 60, monthly: 0, weeks: 0.5, preview: null },
  { id: "socialfeed", cat: "social", name: "Social Feed Aggregator", tagline: "IG · TikTok · X · YouTube in one wall", 
    desc: "Auto-pulled posts with moderation, hashtag filtering, click-through.", oneTime: 100, monthly: 10, weeks: 1, preview: "socialfeed" },
  { id: "challenge", cat: "social", name: "TikTok / Reels Challenge Hub", tagline: "Dance challenge with the AR filter", 
    desc: "Challenge brief, sound link, featured entries, leaderboard by views, prize integration.", oneTime: 150, monthly: 5, weeks: 1.5, preview: "challenge" },
  { id: "sharecards", cat: "social", name: "Dynamic Share Cards", tagline: "Every page shares beautifully", 
    desc: "Server-rendered OG images per city, filter, rank and quiz result.", oneTime: 80, monthly: 5, weeks: 0.5, preview: null },
  { id: "worldmap", cat: "social", name: "Worldwide Fan Map", tagline: "Live pins from every fan check-in", 
    desc: "Real-time globe of fan check-ins and AR captures; per-country counters; heat during shows.", oneTime: 150, monthly: 10, weeks: 2, preview: "worldmap" },
  { id: "discord", cat: "social", name: "Discord / Community Bridge", tagline: "Members-only server with role sync", 
    desc: "Membership tier → Discord role sync, event announcements, bot commands.", oneTime: 100, monthly: 5, weeks: 1, 
    requires: ["fanclub"], preview: null },
  { id: "analytics", cat: "growth", name: "Analytics & Dashboards", tagline: "GA4 + Looker Studio, weekly digest", 
    desc: "Event taxonomy, dashboards for team/label, monthly insight digest.", oneTime: 100, monthly: 10, weeks: 1, preview: null },
  { id: "crm", cat: "growth", name: "CRM Integration", tagline: "Salesforce / HubSpot / Braze", 
    desc: "Bi-directional sync of fan profiles, tags and events.", oneTime: 100, monthly: 5, weeks: 1.5, preview: null },
  { id: "seo", cat: "growth", name: "SEO & Performance Pass", tagline: "Core Web Vitals green", 
    desc: "Technical SEO, structured data, image/CDN optimisation, Lighthouse ≥ 90.", oneTime: 100, monthly: 0, weeks: 1, preview: null },
  { id: "abtest", cat: "growth", name: "A/B Testing & Personalisation", tagline: "Show Miami fans Miami dates first", 
    desc: "Geo/segment-based hero variants and CTA experiments.", oneTime: 100, monthly: 10, weeks: 1, preview: null },
  { id: "pixels", cat: "growth", name: "Ad Pixels & Consent", tagline: "Meta, TikTok, Google, Spotify Ad", 
    desc: "Server-side tagging with consent-mode compliance.", oneTime: 60, monthly: 0, weeks: 0.5, preview: null },
  { id: "hosting", cat: "ops", locked: true, name: "Hosting, CDN & Security", tagline: "Vercel/Cloudflare, global edge", 
    desc: "Edge hosting, DDoS protection, SSL, daily backups, monitoring. Scales for drop-night traffic spikes.", oneTime: 250, monthly: 25, weeks: 0.5, preview: null },
  { id: "legal", cat: "ops", name: "Privacy, Cookies & Age Gate", tagline: "GDPR / CCPA / COPPA ready", 
    desc: "Consent manager, policy pages, data export/delete requests, age gate for AR camera use.", oneTime: 100, monthly: 5, weeks: 0.5, preview: null },
  { id: "a11y", cat: "ops", name: "Accessibility (WCAG 2.2 AA)", tagline: "Everyone gets in", 
    desc: "Audit + remediation, captions, reduced-motion modes, AR alternatives.", oneTime: 100, monthly: 0, weeks: 1, preview: null },
  { id: "support", cat: "ops", name: "Maintenance & Support Retainer", tagline: "Updates, monitoring, small changes", 
    desc: "Monthly hours for content help, dependency updates and new filter QA.", oneTime: 0, monthly: 0, weeks: 0, tier: { label: "Retainer level", options: [
      {"id":"basic","name":"Basic — 4 h/mo","oneTime":0,"monthly":150},
      {"id":"pro","name":"Pro — 10 h/mo, 24h SLA","oneTime":0,"monthly":350},
      {"id":"tour","name":"Tour mode — on-call during shows","oneTime":0,"monthly":700} ] }, preview: null },
  { id: "launch", cat: "ops", name: "Launch Campaign Support", tagline: "Go-live war room", 
    desc: "Load testing, launch-day monitoring, QR/print assets for the AR filters, team training.", oneTime: 150, monthly: 0, weeks: 1, preview: null },
];

/* Pre-built bundles the client can start from */
window.PRESETS = [
  { id: "starter", name: "Starter", blurb: "≈ $5k — landing + AR hub + pre-save + calendar.",
    modules: ["hero", "hosting", "capture", "ar_hub", "ar_face", "presave", "calendar", "legal"] },
  { id: "fan", name: "Fan Experience", blurb: "≈ $8k — adds booth, drops, fan club, rewards, store.",
    modules: ["hero", "hosting", "i18n", "capture", "cms", "ar_hub", "ar_face", "ar_marker", "ar_booth", "ar_drops",
      "presave", "countdown", "smartlinks", "calendar", "tickets", "setlist", "fanclub", "points", "quiz", "fancard", "store", "video", "socialfeed", "legal", "support"] },
  { id: "worldwide", name: "Mr. Worldwide", blurb: "≈ $15k — everything: volumetric AR, portal, livestream, collectibles.",
    modules: "all" },
];

/* Budget bands the proposal is aimed at (one-time build) */
window.BUDGETS = [
  { id: "base", name: "Base", max: 5000 },
  { id: "mid", name: "Mid", max: 8000 },
  { id: "top", name: "Top", max: 15000 },
];
